<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'iThemesSecurity\\Strauss\\ZxcvbnPhp\\' => array($vendorDir . '/bjeavons/zxcvbn-php/src'),
    'iThemesSecurity\\Strauss\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'iThemesSecurity\\Strauss\\StellarWP\\Telemetry\\Views_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/views'),
    'iThemesSecurity\\Strauss\\StellarWP\\Telemetry\\Assets_Dir\\' => array($vendorDir . '/stellarwp/telemetry/src/resources'),
    'iThemesSecurity\\Strauss\\StellarWP\\Telemetry\\' => array($vendorDir . '/stellarwp/telemetry/src/Telemetry'),
    'iThemesSecurity\\Strauss\\StellarWP\\ContainerContract\\' => array($vendorDir . '/stellarwp/container-contract/src'),
    'iThemesSecurity\\Strauss\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'iThemesSecurity\\Strauss\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'iThemesSecurity\\Strauss\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'iThemesSecurity\\Strauss\\Patchstack\\' => array($vendorDir . '/patchstack/firewall/src'),
    'iThemesSecurity\\Strauss\\ParagonIE\\ConstantTime\\' => array($vendorDir . '/paragonie/constant_time_encoding/src'),
    'iThemesSecurity\\Strauss\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\LicensingApiClient\\' => array($vendorDir . '/stellarwp/licensing-api-client/src'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\LicensingApiClientWordPress\\' => array($vendorDir . '/stellarwp/licensing-api-client-wordpress/src'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\Harbor\\Views\\' => array($vendorDir . '/stellarwp/harbor/src/views'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\Harbor\\Build_Dir\\' => array($vendorDir . '/stellarwp/harbor/build'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\Harbor\\Build_Dev_Dir\\' => array($vendorDir . '/stellarwp/harbor/build-dev'),
    'iThemesSecurity\\Strauss\\LiquidWeb\\Harbor\\' => array($vendorDir . '/stellarwp/harbor/src/Harbor'),
    'iThemesSecurity\\Strauss\\FG\\' => array($vendorDir . '/fgrosse/phpasn1/lib'),
    'iThemesSecurity\\Strauss\\Cose\\' => array($vendorDir . '/web-auth/cose-lib/src'),
    'iThemesSecurity\\Strauss\\CBOR\\' => array($vendorDir . '/spomky-labs/cbor-php/src'),
    'iThemesSecurity\\Strauss\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
    'iThemesSecurity\\Strauss\\Assert\\' => array($vendorDir . '/beberlei/assert/lib/Assert'),
    'Symfony\\Polyfill\\Uuid\\' => array($vendorDir . '/symfony/polyfill-uuid'),
);
