<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'iThemesSecurity\\Strauss\\Pimple' => array($vendorDir . '/pimple/pimple/src'),
);
