<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit563d8a1101d31ed0b6527fe8b44d9ed8
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('LearnDash\Notifications\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \LearnDash\Notifications\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit563d8a1101d31ed0b6527fe8b44d9ed8', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \LearnDash\Notifications\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit563d8a1101d31ed0b6527fe8b44d9ed8', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\LearnDash\Notifications\Composer\Autoload\ComposerStaticInit563d8a1101d31ed0b6527fe8b44d9ed8::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
