<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'LearnDash\\Notifications\\StellarWP\\Templates\\' => array($vendorDir . '/stellarwp/templates/src/Templates'),
    'LearnDash\\Notifications\\StellarWP\\Arrays\\' => array($vendorDir . '/stellarwp/arrays/src/Arrays'),
);
