<?php

// autoload_static.php @generated by Composer

namespace LearnDash\Notifications\Composer\Autoload;

class ComposerStaticInit563d8a1101d31ed0b6527fe8b44d9ed8
{
    public static $prefixLengthsPsr4 = array (
        'L' =>
        array (
            'LearnDash\\Notifications\\StellarWP\\Templates\\' => 44,
            'LearnDash\\Notifications\\StellarWP\\Arrays\\' => 41,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'LearnDash\\Notifications\\StellarWP\\Templates\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/templates/src/Templates',
        ),
        'LearnDash\\Notifications\\StellarWP\\Arrays\\' =>
        array (
            0 => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays',
        ),
    );

    public static $classMap = array (
        'LearnDash\\Notifications\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'LearnDash\\Notifications\\StellarWP\\Arrays\\Arr' => __DIR__ . '/..' . '/stellarwp/arrays/src/Arrays/Arr.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Config' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Config.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Part_Cache' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Part_Cache.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Template' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Template.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Templates' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Templates.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Utils\\Conditions' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Conditions.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Utils\\Paths' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Paths.php',
        'LearnDash\\Notifications\\StellarWP\\Templates\\Utils\\Strings' => __DIR__ . '/..' . '/stellarwp/templates/src/Templates/Utils/Strings.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit563d8a1101d31ed0b6527fe8b44d9ed8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit563d8a1101d31ed0b6527fe8b44d9ed8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit563d8a1101d31ed0b6527fe8b44d9ed8::$classMap;

        }, null, ClassLoader::class);
    }
}
