<?php if ( ! defined( 'ABSPATH' ) ) exit; ?>
<h2 name="secure_tokens"><?php _e("Secure Tokens: Biggest xAPI security hole plugged", "grassblade"); ?></h2>

<a href="#pageviews_tracking" onclick="return showHideOptional('grassblade_secure_tokens');"><h3><img src="<?php echo get_bloginfo('wpurl')."/wp-content/plugins/grassblade/img/button.png"; ?>"/><span style="margin-left:10px;"><?php _e("What is Secure Tokens?", "grassblade"); ?></span></h3></a>
<div id="grassblade_secure_tokens"  class="infoblocks"  style="display:none;">
<p>
	<?php printf(__('Whenever an xAPI Content is launched, LRS authentication details including the endpoint, user and password is passed in the URL in a way that can be read by those who understand it. The information can be decoded and misused. Secure Tokens is random authentication tokens generated by GrassBlade when launching the content which has limited life and restricted access. Secure Tokens works only with %s or higher.', 'grassblade'), "<a href='https://www.nextsoftwaresolutions.com/grassblade-lrs-experience-api/' target='_blank'>GrassBlade Cloud LRS (or GrassBlade LRS) v2.1.0</a>"); ?> <br><br>
</p>
</div>

<a href="#pageviews_tracking" onclick="return showHideOptional('grassblade_secure_tokens_levels');"><h3><img src="<?php echo get_bloginfo('wpurl')."/wp-content/plugins/grassblade/img/button.png"; ?>"/><span style="margin-left:10px;"><?php _e("What are the different security levels for Secure Tokens?", "grassblade"); ?></span></h3></a>
<div id="grassblade_secure_tokens_levels"  class="infoblocks"  style="display:none;">
<p>
	<?php printf(__('Currently there are three security levels. All these level have a 24 hour token life:', 'grassblade')); ?> <br>
	<?php printf(__('1. <b>Low:</b> Access to user\'s own statements only.', 'grassblade')); ?> <br>
	<?php printf(__('2. <b>Medium:</b> Access to user\'s own statements for the specific content only.', 'grassblade')); ?> <br>
	<?php printf(__('3. <b>High:</b> Access to user\'s own statements for the specific content, when accessed from the IP of the user this token was generated for.', 'grassblade')); ?> <br>
</p>
</div>